name: docker static website
on:
  push:
    tags:
      - v*

jobs:
  get-static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Generate Changelog
        id: changelog
        uses: jaywcjlove/changelog-generator@main
        with:
          filter-author: (小弟调调™)
          filter: (^[\s]+?[R|r]elease)|(^[R|r]elease)

      # Create Docker Image
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image:tags
        uses: docker/build-push-action@v3
        if: steps.create_tag.outputs.successful
        with:
          push: true
          context: .
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_USER }}/linux-command:'${{secrets.GITHUB_REF#refs/tags/v}}'
